"""
Data pertanyaan untuk seed database.
Format: (pertanyaan, jawaban, penjelasan, tags)
"""

SEED_QUESTIONS = {
    "Python Dasar - Easy": [
        ("Apa itu variabel?", "Wadah untuk menyimpan nilai/data",
         "Variabel menyimpan data yang bisa berubah nilainya selama program berjalan. Contoh: nama = 'Budi'",
         "konsep,dasar"),
        ("Apa output dari print(2+3)?", "5",
         "Python menghitung 2+3=5 karena keduanya bertipe integer, lalu print() menampilkannya.",
         "angka,output"),
        ("Apa tipe data dari 'hello'?", "str (string)",
         "Tanda kutip menandakan data bertipe string (teks), bukan angka.",
         "tipe_data,dasar"),
        ("Apa fungsi print()?", "Menampilkan output ke layar",
         "print() menampilkan apapun yang ada di dalam kurungnya ke layar console.",
         "fungsi,dasar"),
        ("Apa itu integer?", "Bilangan bulat tanpa desimal",
         "Integer adalah bilangan bulat seperti 1, 100, -5. Tidak ada koma atau titik desimal.",
         "tipe_data,angka"),
        ("Apa output dari len('abc')?", "3",
         "len() menghitung jumlah karakter: 'a','b','c' = 3 karakter.",
         "fungsi,string"),
        ("Apa itu string?", "Teks yang diapit tanda kutip",
         "String adalah urutan karakter yang diapit kutip tunggal '...' atau ganda \"...\".",
         "tipe_data,dasar"),
        ("Apa operator penambahan?", "+",
         "Operator + menjumlahkan angka atau menggabungkan string (concatenation).",
         "operator,dasar"),
        ("Apa itu boolean?", "Tipe data True atau False",
         "Boolean hanya punya dua nilai: True atau False. Dipakai untuk kondisi dan logika.",
         "tipe_data,logika"),
        ("Apa output dari 10 % 3?", "1 (sisa bagi)",
         "Modulo (%) menghasilkan sisa pembagian: 10÷3=3 sisa 1.",
         "angka,operator"),
        ("Apa fungsi input()?", "Menerima input dari pengguna",
         "input() membaca teks yang diketik pengguna dari keyboard dan mengembalikannya sebagai string.",
         "fungsi,dasar"),
        ("Apa itu float?", "Bilangan desimal",
         "Float adalah bilangan dengan titik desimal seperti 3.14 atau -0.5.",
         "tipe_data,angka"),
        ("Apa output dari 'a' + 'b'?", "ab (concatenation)",
         "Operator + pada string menggabungkan teks, bukan menjumlahkan.",
         "string,operator"),
        ("Apa itu comment di Python?", "Teks setelah # yang tidak dieksekusi",
         "Comment diabaikan Python, berguna untuk dokumentasi dan catatan kode.",
         "dasar,syntax"),
        ("Apa keyword untuk membuat kondisi?", "if",
         "if menjalankan blok kode hanya jika kondisi bernilai True.",
         "logika,keyword"),
    ],
    "Python Dasar - Medium": [
        ("Apa perbedaan list dan tuple?", "List mutable, tuple immutable",
         "List bisa diubah setelah dibuat (tambah/hapus elemen), tuple tidak bisa. List pakai [], tuple pakai ().",
         "struktur_data,konsep"),
        ("Apa fungsi def?", "Keyword untuk mendefinisikan fungsi",
         "def membuat blok kode yang bisa dipanggil berulang kali dengan nama tertentu.",
         "fungsi,keyword"),
        ("Apa itu dictionary?", "Struktur data key-value pair",
         "Dictionary menyimpan pasangan kunci-nilai. Contoh: {'nama': 'Budi', 'umur': 20}.",
         "struktur_data,konsep"),
        ("Apa output dari range(3)?", "0, 1, 2",
         "range(3) menghasilkan urutan angka dari 0 sampai 2 (tidak termasuk 3).",
         "fungsi,angka"),
        ("Apa itu slicing [1:4]?", "Mengambil elemen indeks 1 sampai 3",
         "Slicing mengambil bagian dari list/string. Indeks awal termasuk, indeks akhir tidak termasuk.",
         "struktur_data,teknik"),
        ("Apa perbedaan == dan is?", "== cek nilai, is cek objek",
         "== membandingkan nilai (value), is membandingkan apakah dua variabel menunjuk objek yang sama di memori.",
         "operator,konsep"),
        ("Apa itu f-string?", "Format string dengan {variabel}",
         "f-string memungkinkan menyisipkan variabel langsung ke dalam string: f'Halo {nama}'.",
         "string,teknik"),
        ("Apa itu method?", "Fungsi yang terikat pada objek/class",
         "Method adalah fungsi yang dimiliki oleh objek. Contoh: list.append(), str.upper().",
         "oop,konsep"),
        ("Apa output dari bool('')?", "False",
         "String kosong, angka 0, list kosong, dan None semuanya bernilai False (falsy).",
         "logika,tipe_data"),
        ("Apa itu exception handling?", "Menangani error dengan try-except",
         "try-except menangkap error agar program tidak crash, lalu menangani error tersebut dengan graceful.",
         "error_handling,konsep"),
        ("Apa itu module?", "File .py yang bisa di-import",
         "Module adalah file Python berisi kode yang bisa dipakai ulang di file lain dengan import.",
         "struktur,konsep"),
        ("Apa fungsi enumerate()?", "Mengembalikan index dan value sekaligus",
         "enumerate() mengembalikan pasangan (index, elemen) saat iterasi. Berguna untuk loop dengan counter.",
         "fungsi,teknik"),
        ("Apa itu list comprehension?", "Cara singkat membuat list dalam satu baris",
         "List comprehension membuat list dari iterasi dalam satu baris: [x*2 for x in range(5)].",
         "teknik,pythonic"),
        ("Apa output dari sorted([3,1,2])?", "[1, 2, 3]",
         "sorted() mengembalikan list baru yang sudah diurutkan dari kecil ke besar.",
         "fungsi,list"),
        ("Apa itu lambda?", "Fungsi anonim satu baris",
         "Lambda membuat fungsi kecil tanpa nama dalam satu baris: lambda x: x*2.",
         "fungsi,teknik"),
    ],
    "Python Dasar - Hard": [
        ("Apa itu decorator?", "Fungsi yang memodifikasi perilaku fungsi lain",
         "Decorator pakai simbol @ di atas fungsi. Ia 'membungkus' fungsi lama dengan kode baru tanpa mengubah fungsi aslinya.",
         "advanced,oop"),
        ("Apa perbedaan deep copy dan shallow copy?", "Deep copy menyalin semua level, shallow hanya level pertama",
         "Shallow copy hanya menyalin referensi objek di dalamnya, deep copy membuat salinan sepenuhnya termasuk objek bersarang.",
         "advanced,memori"),
        ("Apa itu generator?", "Fungsi yang yield nilai satu per satu, hemat memori",
         "Generator menghasilkan nilai satu per satu dengan yield, tanpa menyimpan semua nilai di memori sekaligus.",
         "advanced,memori"),
        ("Apa itu *args dan **kwargs?", "*args terima argumen posisi, **kwargs terima keyword arguments",
         "*args mengumpulkan argumen posisi menjadi tuple, **kwargs mengumpulkan argumen bernama menjadi dictionary.",
         "fungsi,advanced"),
        ("Apa itu metaclass?", "Class dari class, mengontrol pembuatan class",
         "Metaclass mengontrol bagaimana class dibuat dan berperilaku. type() adalah metaclass default Python.",
         "advanced,oop"),
        ("Apa itu context manager?", "Objek dengan __enter__ dan __exit__, dipakai dengan with",
         "Context manager mengelola setup dan cleanup otomatis. Contoh: with open('file.txt') as f.",
         "advanced,teknik"),
        ("Apa perbedaan threading dan multiprocessing?", "Threading share memory, multiprocessing punya memory sendiri",
         "Threading cocok untuk I/O bound, multiprocessing untuk CPU bound karena menghindari GIL.",
         "advanced,concurrency"),
        ("Apa itu GIL?", "Global Interpreter Lock, mencegah multi-threading sejati di CPython",
         "GIL memastikan hanya satu thread yang mengeksekusi bytecode Python pada satu waktu, membatasi paralelisme.",
         "advanced,concurrency"),
        ("Apa itu dunder method?", "Method khusus seperti __init__, __str__, __len__",
         "Dunder (double underscore) method memungkinkan class mengimplementasikan perilaku khusus seperti operator dan built-in.",
         "oop,advanced"),
        ("Apa itu closure?", "Fungsi inner yang mengingat variabel dari outer scope",
         "Closure terjadi saat fungsi inner 'mengingat' variabel dari fungsi outer meskipun outer sudah selesai dieksekusi.",
         "advanced,fungsi"),
        ("Apa itu abstract class?", "Class yang tidak bisa diinstansiasi langsung, pakai ABC",
         "Abstract class mendefinisikan interface yang harus diimplementasikan oleh subclass. Pakai modul abc.",
         "oop,advanced"),
        ("Apa perbedaan @staticmethod dan @classmethod?", "Staticmethod tidak terima self/cls, classmethod terima cls",
         "@staticmethod tidak perlu akses instance atau class, @classmethod bisa akses class via parameter cls.",
         "oop,advanced"),
        ("Apa itu descriptor protocol?", "__get__, __set__, __delete__ untuk kontrol atribut",
         "Descriptor mengontrol bagaimana atribut diakses, di-set, dan dihapus. Property di Python menggunakan descriptor.",
         "advanced,oop"),
        ("Apa itu MRO?", "Method Resolution Order, urutan pencarian method di inheritance",
         "MRO menentukan urutan class mana yang dicari terlebih dahulu saat memanggil method pada inheritance bertingkat.",
         "oop,advanced"),
        ("Apa itu asyncio?", "Library untuk asynchronous programming dengan async/await",
         "asyncio memungkinkan menjalankan banyak operasi I/O secara bersamaan tanpa membuat thread terpisah.",
         "advanced,concurrency"),
    ],
    "Matematika SD": [
        ("Berapa 7 × 8?", "56",
         "Perkalian adalah penjumlahan berulang: 7+7+7+7+7+7+7+7 = 56.",
         "angka,perkalian"),
        ("Rumus luas persegi panjang?", "panjang × lebar",
         "Luas = panjang dikali lebar. Satuannya cm², m², dll.",
         "geometri,rumus"),
        ("Berapa 144 ÷ 12?", "12",
         "Pembagian adalah kebalikan perkalian: 12 × 12 = 144.",
         "angka,pembagian"),
        ("Apa itu bilangan prima?", "Bilangan > 1 yang hanya habis dibagi 1 dan dirinya sendiri",
         "Contoh: 2, 3, 5, 7, 11. Bilangan 4 bukan prima karena bisa dibagi 2.",
         "konsep,angka"),
        ("Rumus keliling persegi?", "4 × sisi",
         "Persegi punya 4 sisi sama panjang, jadi keliling = 4 dikali panjang satu sisi.",
         "geometri,rumus"),
        ("Berapa 25% dari 200?", "50",
         "25% = 25/100 = 1/4. Jadi 200 × 1/4 = 50.",
         "angka,persen"),
        ("Apa itu pecahan?", "Bilangan dalam bentuk a/b",
         "Pecahan menyatakan bagian dari keseluruhan. a = pembilang, b = penyebut.",
         "konsep,pecahan"),
        ("Rumus luas segitiga?", "½ × alas × tinggi",
         "Luas segitiga = setengah dari perkalian alas dan tinggi.",
         "geometri,rumus"),
        ("Berapa √81?", "9",
         "Akar kuadrat 81 adalah bilangan yang jika dikalikan dirinya sendiri hasilnya 81: 9×9=81.",
         "angka,akar"),
        ("Apa itu KPK?", "Kelipatan Persekutuan Terkecil",
         "KPK adalah bilangan terkecil yang bisa dibagi oleh kedua bilangan tersebut.",
         "konsep,angka"),
        ("Berapa 3² + 4²?", "25",
         "3²=9, 4²=16, jadi 9+16=25. Ini juga sisi miring segitiga siku-siku (Pythagoras).",
         "angka,pangkat"),
        ("Rumus volume kubus?", "sisi × sisi × sisi (s³)",
         "Volume kubus = sisi pangkat 3. Satuannya cm³, m³.",
         "geometri,rumus"),
        ("Berapa FPB dari 12 dan 18?", "6",
         "FPB adalah bilangan terbesar yang bisa membagi keduanya: 12÷6=2, 18÷6=3.",
         "konsep,angka"),
        ("Apa itu bilangan genap?", "Bilangan yang habis dibagi 2",
         "Contoh: 2, 4, 6, 8, 10. Bilangan ganjil: 1, 3, 5, 7, 9.",
         "konsep,angka"),
        ("Berapa 15 + 27 + 8?", "50",
         "Penjumlahan: 15+27=42, lalu 42+8=50.",
         "angka,penjumlahan"),
    ],
    "Matematika SMP": [
        ("Rumus luas lingkaran?", "π × r²",
         "π ≈ 3.14, r = jari-jari. Luas = π dikali jari-jari kuadrat.",
         "geometri,rumus"),
        ("Berapa (-3)² ?", "9",
         "Bilangan negatif dipangkatkan 2 menjadi positif: (-3)×(-3)=9.",
         "angka,pangkat"),
        ("Apa itu variabel dalam aljabar?", "Huruf yang mewakili bilangan belum diketahui",
         "Variabel seperti x, y, z mewakili nilai yang belum kita ketahui dalam persamaan.",
         "aljabar,konsep"),
        ("Rumus Pythagoras?", "a² + b² = c²",
         "Pada segitiga siku-siku, kuadrat sisi miring = jumlah kuadrat kedua sisi lainnya.",
         "geometri,rumus"),
        ("Berapa log₁₀(1000)?", "3",
         "log₁₀(1000) = 3 karena 10³ = 1000.",
         "angka,logaritma"),
        ("Apa itu persamaan linear satu variabel?", "Persamaan dengan satu huruf berpangkat 1",
         "Contoh: 2x+3=7. Solusinya x=2. Disebut linear karena pangkat variabelnya 1.",
         "aljabar,konsep"),
        ("Rumus keliling lingkaran?", "2 × π × r",
         "Keliling = 2πr atau πd (d = diameter). π ≈ 3.14.",
         "geometri,rumus"),
        ("Berapa 5! (5 faktorial)?", "120",
         "5! = 5×4×3×2×1 = 120. Faktorial dipakai di kombinatorika.",
         "angka,faktorial"),
        ("Apa itu perbandingan senilai?", "Jika a naik maka b juga naik, a/b = konstan",
         "Contoh: harga dan jumlah barang. Makin banyak barang, makin besar total harga.",
         "konsep,perbandingan"),
        ("Rumus volume tabung?", "π × r² × t",
         "Volume tabung = luas alas (lingkaran) dikali tinggi.",
         "geometri,rumus"),
        ("Berapa sin 30°?", "½ atau 0.5",
         "sin 30° = 1/2. Ini salah satu sudut istimewa dalam trigonometri.",
         "trigonometri,rumus"),
        ("Apa itu himpunan?", "Kumpulan objek yang terdefinisi dengan jelas",
         "Himpunan ditulis dengan kurung kurawal: A = {1, 2, 3}.",
         "konsep,himpunan"),
        ("Rumus gradien garis lurus?", "(y₂-y₁)/(x₂-x₁)",
         "Gradien = perubahan y dibagi perubahan x. Menunjukkan kemiringan garis.",
         "aljabar,rumus"),
        ("Berapa ∛27?", "3",
         "Akar pangkat 3 dari 27 adalah 3, karena 3×3×3=27.",
         "angka,akar"),
        ("Apa itu bilangan rasional?", "Bilangan yang bisa ditulis sebagai a/b, b≠0",
         "Contoh: 1/2, 0.75, -3. Bilangan irasional: π, √2.",
         "konsep,angka"),
    ],
    "Matematika SMA": [
        ("Apa itu turunan?", "Laju perubahan sesaat suatu fungsi",
         "Turunan mengukur seberapa cepat fungsi berubah di suatu titik. Notasi: f'(x) atau dy/dx.",
         "kalkulus,konsep"),
        ("Rumus integral tentu?", "∫[a,b] f(x)dx = F(b) - F(a)",
         "Integral tentu menghitung luas area di bawah kurva antara batas a dan b.",
         "kalkulus,rumus"),
        ("Rumus barisan aritmatika?", "Un = a + (n-1)b",
         "Suku ke-n = suku pertama + (n-1) dikali beda. Contoh: 2, 5, 8, 11... (b=3).",
         "barisan,rumus"),
        ("Rumus deret geometri tak hingga?", "S∞ = a/(1-r), |r|<1",
         "Deret geometri konvergen jika rasio |r|<1. Jumlah tak hingganya = a/(1-r).",
         "barisan,rumus"),
        ("Apa itu limit?", "Nilai yang didekati fungsi saat x mendekati suatu titik",
         "Limit tidak harus sama dengan nilai fungsi di titik tersebut. Notasi: lim x→a f(x).",
         "kalkulus,konsep"),
        ("Rumus kombinasi C(n,r)?", "n! / (r!(n-r)!)",
         "Kombinasi memilih r objek dari n tanpa memperhatikan urutan.",
         "statistika,rumus"),
        ("Apa itu matriks identitas?", "Matriks diagonal dengan semua elemen diagonal = 1",
         "Matriks identitas I: dikalikan matriks apapun hasilnya matriks itu sendiri.",
         "aljabar_linear,konsep"),
        ("Rumus aturan cosinus?", "c² = a² + b² - 2ab·cos(C)",
         "Generalisasi Pythagoras untuk segitiga sembarang (tidak harus siku-siku).",
         "trigonometri,rumus"),
        ("Apa itu peluang bersyarat?", "P(A|B) = P(A∩B)/P(B)",
         "Peluang kejadian A terjadi dengan syarat kejadian B sudah terjadi.",
         "statistika,konsep"),
        ("Rumus determinan 2×2?", "ad - bc",
         "Untuk matriks [[a,b],[c,d]], determinan = ad - bc.",
         "aljabar_linear,rumus"),
        ("Apa itu asimtot?", "Garis yang didekati kurva tapi tidak pernah disentuh",
         "Asimtot bisa horizontal, vertikal, atau miring. Contoh: y=1/x punya asimtot x=0 dan y=0.",
         "kalkulus,konsep"),
        ("Teorema L'Hopital digunakan untuk?", "Limit bentuk tak tentu 0/0 atau ∞/∞",
         "Jika limit menghasilkan 0/0 atau ∞/∞, turunkan pembilang dan penyebut lalu hitung ulang.",
         "kalkulus,teknik"),
        ("Rumus persamaan kuadrat?", "x = (-b ± √(b²-4ac)) / 2a",
         "Rumus abc untuk mencari akar persamaan ax²+bx+c=0.",
         "aljabar,rumus"),
        ("Apa itu eigenvalue?", "Skalar λ dimana Av = λv untuk vektor v ≠ 0",
         "Eigenvalue menunjukkan seberapa besar vektor di-scale oleh transformasi matriks.",
         "aljabar_linear,advanced"),
        ("Rumus Euler?", "e^(iπ) + 1 = 0",
         "Menghubungkan 5 konstanta fundamental: e, i, π, 1, 0. Dianggap rumus terindah dalam matematika.",
         "advanced,rumus"),
    ],
    "Bahasa Inggris TOEFL - Easy": [
        ("Arti 'happy'?", "Senang / bahagia",
         "Happy adalah kata sifat dasar untuk perasaan positif. Contoh: I am happy today.",
         "vocab,dasar"),
        ("Lawan kata 'big'?", "Small",
         "Big = besar, Small = kecil. Pasangan antonim dasar.",
         "vocab,antonim"),
        ("Arti 'beautiful'?", "Cantik / indah",
         "Beautiful mendeskripsikan sesuatu yang menarik secara visual.",
         "vocab,dasar"),
        ("Sinonim 'fast'?", "Quick / rapid",
         "Fast, quick, rapid semuanya berarti cepat dengan nuansa sedikit berbeda.",
         "vocab,sinonim"),
        ("Arti 'difficult'?", "Sulit / susah",
         "Difficult = sulit. Sinonim: hard, challenging. Antonim: easy.",
         "vocab,dasar"),
        ("Lawan kata 'hot'?", "Cold",
         "Hot = panas, Cold = dingin. Pasangan antonim suhu.",
         "vocab,antonim"),
        ("Arti 'important'?", "Penting",
         "Important = penting, signifikan. Contoh: This is an important meeting.",
         "vocab,dasar"),
        ("Sinonim 'good'?", "Excellent / fine",
         "Good punya banyak sinonim: excellent, great, fine, wonderful.",
         "vocab,sinonim"),
        ("Arti 'dangerous'?", "Berbahaya",
         "Dangerous = berbahaya, berisiko. Contoh: That road is dangerous at night.",
         "vocab,dasar"),
        ("Lawan kata 'rich'?", "Poor",
         "Rich = kaya, Poor = miskin. Pasangan antonim ekonomi.",
         "vocab,antonim"),
        ("Arti 'successful'?", "Sukses / berhasil",
         "Successful = berhasil mencapai tujuan. Bentuk noun: success.",
         "vocab,dasar"),
        ("Sinonim 'start'?", "Begin / commence",
         "Start, begin, commence, initiate semuanya berarti memulai.",
         "vocab,sinonim"),
        ("Arti 'necessary'?", "Diperlukan / perlu",
         "Necessary = diperlukan, wajib ada. Sinonim: essential, required.",
         "vocab,dasar"),
        ("Lawan kata 'increase'?", "Decrease",
         "Increase = meningkat, Decrease = menurun. Sering dipakai di grafik.",
         "vocab,antonim"),
        ("Arti 'available'?", "Tersedia",
         "Available = tersedia, bisa diakses. Contoh: The book is available online.",
         "vocab,dasar"),
    ],
    "Bahasa Inggris TOEFL - Medium": [
        ("Arti 'ambiguous'?", "Bermakna ganda / tidak jelas",
         "Ambiguous = punya lebih dari satu interpretasi. Contoh: His answer was ambiguous.",
         "vocab,toefl"),
        ("Sinonim 'ubiquitous'?", "Omnipresent / found everywhere",
         "Ubiquitous = ada di mana-mana. Contoh: Smartphones are ubiquitous today.",
         "vocab,toefl,sinonim"),
        ("Arti 'mitigate'?", "Mengurangi / meredakan",
         "Mitigate = mengurangi dampak negatif. Contoh: mitigate risks, mitigate damage.",
         "vocab,toefl"),
        ("Lawan kata 'benevolent'?", "Malevolent",
         "Benevolent = baik hati, Malevolent = jahat/berniat buruk. Prefix bene- vs male-.",
         "vocab,toefl,antonim"),
        ("Arti 'pragmatic'?", "Praktis / realistis",
         "Pragmatic = fokus pada hasil praktis, bukan teori. Sinonim: practical, realistic.",
         "vocab,toefl"),
        ("Sinonim 'meticulous'?", "Thorough / painstaking",
         "Meticulous = sangat teliti dan detail. Contoh: She was meticulous in her research.",
         "vocab,toefl,sinonim"),
        ("Arti 'exacerbate'?", "Memperburuk / memperparah",
         "Exacerbate = membuat situasi lebih buruk. Antonim: alleviate, improve.",
         "vocab,toefl"),
        ("Apa itu passive voice?", "Subjek menerima aksi: The book was read by her",
         "Passive: subjek menerima aksi. Active: subjek melakukan aksi. Passive = be + V3.",
         "grammar,toefl"),
        ("Arti 'diligent'?", "Rajin / tekun",
         "Diligent = bekerja dengan tekun dan konsisten. Sinonim: hardworking, industrious.",
         "vocab,toefl"),
        ("Sinonim 'ephemeral'?", "Transient / short-lived",
         "Ephemeral = berlangsung sangat singkat. Contoh: ephemeral beauty, ephemeral fame.",
         "vocab,toefl,sinonim"),
        ("Arti 'resilient'?", "Tangguh / mampu bangkit",
         "Resilient = mampu pulih dari kesulitan. Contoh: resilient economy, resilient person.",
         "vocab,toefl"),
        ("Apa itu conditional type 3?", "If + past perfect, would have + V3",
         "Conditional 3 untuk penyesalan masa lalu: If I had studied, I would have passed.",
         "grammar,toefl"),
        ("Arti 'comprehensive'?", "Menyeluruh / lengkap",
         "Comprehensive = mencakup semua aspek. Contoh: comprehensive review, comprehensive guide.",
         "vocab,toefl"),
        ("Sinonim 'obsolete'?", "Outdated / no longer in use",
         "Obsolete = sudah kuno, tidak dipakai lagi. Contoh: obsolete technology.",
         "vocab,toefl,sinonim"),
        ("Arti 'conundrum'?", "Teka-teki / masalah membingungkan",
         "Conundrum = masalah yang sulit dipecahkan. Sinonim: puzzle, dilemma.",
         "vocab,toefl"),
    ],
    "Bahasa Inggris TOEFL - Hard": [
        ("Arti 'sycophant'?", "Penjilat / orang yang menjilat atasan",
         "Sycophant = orang yang memuji berlebihan untuk keuntungan pribadi.",
         "vocab,toefl,advanced"),
        ("Sinonim 'perspicacious'?", "Astute / shrewd / insightful",
         "Perspicacious = tajam dalam memahami situasi. Sinonim: perceptive, discerning.",
         "vocab,toefl,advanced,sinonim"),
        ("Arti 'obsequious'?", "Terlalu menurut / servile",
         "Obsequious = terlalu patuh dan menjilat. Lebih negatif dari obedient.",
         "vocab,toefl,advanced"),
        ("Lawan kata 'magnanimous'?", "Petty / vindictive",
         "Magnanimous = besar hati, pemaaf. Antonim: petty (kecil hati), vindictive (pendendam).",
         "vocab,toefl,advanced,antonim"),
        ("Arti 'iconoclast'?", "Orang yang menentang tradisi/keyakinan umum",
         "Iconoclast = orang yang menyerang kepercayaan atau institusi yang sudah mapan.",
         "vocab,toefl,advanced"),
        ("Sinonim 'laconic'?", "Terse / concise / brief",
         "Laconic = menggunakan sedikit kata. Sinonim: succinct, pithy. Antonim: verbose.",
         "vocab,toefl,advanced,sinonim"),
        ("Arti 'pusillanimous'?", "Pengecut / lacking courage",
         "Pusillanimous = sangat penakut, tidak punya keberanian. Sinonim: cowardly.",
         "vocab,toefl,advanced"),
        ("Apa itu subjunctive mood?", "Bentuk kata kerja untuk hipotesis: If I were...",
         "Subjunctive untuk situasi tidak nyata: If I were rich, I wish he were here.",
         "grammar,toefl,advanced"),
        ("Arti 'quixotic'?", "Idealistis tapi tidak realistis",
         "Quixotic = idealis yang tidak praktis. Berasal dari karakter Don Quixote.",
         "vocab,toefl,advanced"),
        ("Sinonim 'verisimilitude'?", "Plausibility / appearance of truth",
         "Verisimilitude = kemiripan dengan kebenaran. Dipakai di sastra dan film.",
         "vocab,toefl,advanced,sinonim"),
        ("Arti 'sesquipedalian'?", "Menggunakan kata-kata panjang / bertele-tele",
         "Sesquipedalian = cenderung menggunakan kata-kata yang sangat panjang.",
         "vocab,toefl,advanced"),
        ("Apa itu dangling modifier?", "Modifier yang tidak jelas merujuk ke subjek mana",
         "Dangling modifier: 'Walking to school, the rain started.' Siapa yang walking?",
         "grammar,toefl,advanced"),
        ("Arti 'recalcitrant'?", "Bandel / sulit dikendalikan",
         "Recalcitrant = sangat keras kepala, menolak patuh. Sinonim: defiant, unruly.",
         "vocab,toefl,advanced"),
        ("Sinonim 'sanguine'?", "Optimistic / cheerful",
         "Sanguine = optimis dan ceria, terutama di situasi sulit.",
         "vocab,toefl,advanced,sinonim"),
        ("Arti 'perfunctory'?", "Dilakukan secara asal-asalan / tanpa minat",
         "Perfunctory = dilakukan tanpa perhatian, sekadar formalitas. Contoh: perfunctory smile.",
         "vocab,toefl,advanced"),
    ],
}